-- Desativar temporariamente as restrições de chave estrangeira
SET REFERENTIAL_INTEGRITY FALSE;

-- Remover todas as tabelas
DROP TABLE IF EXISTS visits;

-- Reativar as restrições
SET REFERENTIAL_INTEGRITY TRUE;

-- Agora crie as tabelas na ordem correta
CREATE TABLE visits (
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pet_id      INTEGER,
    visit_date  DATE,
    description VARCHAR(255)
);
CREATE INDEX visits_pet_id ON visits (pet_id);